table HR_Analytics
	lineageTag: 1d7576e3-3223-4676-a96f-eea1190b5aac

	measure AttritionRate = SUM(HR_Analytics[AttritionCount])/SUM(HR_Analytics[EmployeeCount])
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: c15b9651-a8d8-439e-8dcf-2db37e9da827

	column EmpID
		dataType: string
		lineageTag: ba36bae3-cafe-4b78-b497-b4155c57977e
		summarizeBy: none
		sourceColumn: EmpID

		annotation SummarizationSetBy = Automatic

	column Age
		dataType: int64
		formatString: 0
		lineageTag: 3a82bd91-0b4e-4294-8a42-48af18408c45
		summarizeBy: sum
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column AgeGroup
		dataType: string
		lineageTag: b07b3bc7-3e5b-4f0f-9c69-67a9506dbae8
		summarizeBy: none
		sourceColumn: AgeGroup

		annotation SummarizationSetBy = Automatic

	column Attrition
		dataType: string
		lineageTag: db85f829-fe16-4042-b5b9-56e361fb9b09
		summarizeBy: none
		sourceColumn: Attrition

		annotation SummarizationSetBy = Automatic

	column BusinessTravel
		dataType: string
		lineageTag: 9f11e034-cc94-4932-a6b9-c843d243cb1c
		summarizeBy: none
		sourceColumn: BusinessTravel

		annotation SummarizationSetBy = Automatic

	column DailyRate
		dataType: int64
		formatString: 0
		lineageTag: 9ce9d3e0-f956-4e82-9024-ead4a710953d
		summarizeBy: sum
		sourceColumn: DailyRate

		annotation SummarizationSetBy = Automatic

	column Department
		dataType: string
		lineageTag: e29820c2-908a-45ee-94bf-1750fbd41d7a
		summarizeBy: none
		sourceColumn: Department

		annotation SummarizationSetBy = Automatic

	column DistanceFromHome
		dataType: int64
		formatString: 0
		lineageTag: 60431213-d530-4f6c-bafc-899915f7f4f3
		summarizeBy: sum
		sourceColumn: DistanceFromHome

		annotation SummarizationSetBy = Automatic

	column Education
		dataType: int64
		formatString: 0
		lineageTag: c184ac12-40de-497e-8f95-a5321abbd894
		summarizeBy: sum
		sourceColumn: Education

		annotation SummarizationSetBy = Automatic

	column EducationField
		dataType: string
		lineageTag: 4ee99289-17d3-4d99-8be0-b61761f23e69
		summarizeBy: none
		sourceColumn: EducationField

		annotation SummarizationSetBy = Automatic

	column EmployeeCount
		dataType: int64
		formatString: 0
		lineageTag: 17834065-7e7f-4a15-a2c0-40d427b3088e
		summarizeBy: sum
		sourceColumn: EmployeeCount

		annotation SummarizationSetBy = Automatic

	column EmployeeNumber
		dataType: int64
		formatString: 0
		lineageTag: a4b7a508-ce89-4ade-af11-1d94dfb07c02
		summarizeBy: sum
		sourceColumn: EmployeeNumber

		annotation SummarizationSetBy = Automatic

	column EnvironmentSatisfaction
		dataType: int64
		formatString: 0
		lineageTag: 21d499f4-0b1b-47b1-8609-fc424fc329d8
		summarizeBy: sum
		sourceColumn: EnvironmentSatisfaction

		annotation SummarizationSetBy = Automatic

	column Gender
		dataType: string
		lineageTag: fb88bf73-05ce-4134-917f-366c61f33c3c
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	column HourlyRate
		dataType: int64
		formatString: 0
		lineageTag: 4fd66ff2-dfb0-440c-b23b-b7fe897a0e53
		summarizeBy: sum
		sourceColumn: HourlyRate

		annotation SummarizationSetBy = Automatic

	column JobInvolvement
		dataType: int64
		formatString: 0
		lineageTag: fe26d820-3ea5-48c3-bc2c-434b2b17d632
		summarizeBy: sum
		sourceColumn: JobInvolvement

		annotation SummarizationSetBy = Automatic

	column JobLevel
		dataType: int64
		formatString: 0
		lineageTag: c3e7ac20-1859-4e0d-b7ae-6af82a95fb12
		summarizeBy: sum
		sourceColumn: JobLevel

		annotation SummarizationSetBy = Automatic

	column JobRole
		dataType: string
		lineageTag: 6125cf56-4b49-48dd-b4e1-cf449b8fc838
		summarizeBy: none
		sourceColumn: JobRole

		annotation SummarizationSetBy = Automatic

	column JobSatisfaction
		dataType: int64
		formatString: 0
		lineageTag: d1ce1169-4602-472e-9fc9-c6a88a65a1e6
		summarizeBy: sum
		sourceColumn: JobSatisfaction

		annotation SummarizationSetBy = Automatic

	column MaritalStatus
		dataType: string
		lineageTag: 13984390-26ce-4a19-941c-30db189a840c
		summarizeBy: none
		sourceColumn: MaritalStatus

		annotation SummarizationSetBy = Automatic

	column MonthlyIncome
		dataType: int64
		formatString: 0
		lineageTag: c2ded40c-1e6a-476e-8038-015864e0ece5
		summarizeBy: sum
		sourceColumn: MonthlyIncome

		annotation SummarizationSetBy = Automatic

	column SalarySlab
		dataType: string
		lineageTag: 95c7998d-6c21-4010-87d4-9489196ba849
		summarizeBy: none
		sourceColumn: SalarySlab

		annotation SummarizationSetBy = Automatic

	column MonthlyRate
		dataType: int64
		formatString: 0
		lineageTag: f9ec5882-5cb3-4fb3-ba07-94df59e155ef
		summarizeBy: sum
		sourceColumn: MonthlyRate

		annotation SummarizationSetBy = Automatic

	column NumCompaniesWorked
		dataType: int64
		formatString: 0
		lineageTag: c5d1ea04-8fd0-456d-adc2-348356a86cdf
		summarizeBy: sum
		sourceColumn: NumCompaniesWorked

		annotation SummarizationSetBy = Automatic

	column Over18
		dataType: string
		lineageTag: a2303cde-5e4e-494d-923c-e708d0e72e59
		summarizeBy: none
		sourceColumn: Over18

		annotation SummarizationSetBy = Automatic

	column OverTime
		dataType: string
		lineageTag: f41afe82-cc03-42c3-9845-d49b2e3d0199
		summarizeBy: none
		sourceColumn: OverTime

		annotation SummarizationSetBy = Automatic

	column PercentSalaryHike
		dataType: int64
		formatString: 0
		lineageTag: bd0c95eb-de6a-4388-9354-b41703e760a3
		summarizeBy: sum
		sourceColumn: PercentSalaryHike

		annotation SummarizationSetBy = Automatic

	column PerformanceRating
		dataType: int64
		formatString: 0
		lineageTag: 7647d63f-f261-4b91-ac36-2b3ee46c0347
		summarizeBy: sum
		sourceColumn: PerformanceRating

		annotation SummarizationSetBy = Automatic

	column RelationshipSatisfaction
		dataType: int64
		formatString: 0
		lineageTag: 52bac6ad-d36d-45c2-bb41-9601799f84c2
		summarizeBy: sum
		sourceColumn: RelationshipSatisfaction

		annotation SummarizationSetBy = Automatic

	column StandardHours
		dataType: int64
		formatString: 0
		lineageTag: 87095818-4bba-4f21-bd40-94f476c32f36
		summarizeBy: sum
		sourceColumn: StandardHours

		annotation SummarizationSetBy = Automatic

	column StockOptionLevel
		dataType: int64
		formatString: 0
		lineageTag: 1471b439-dd30-4d6b-9191-75150b7f720d
		summarizeBy: sum
		sourceColumn: StockOptionLevel

		annotation SummarizationSetBy = Automatic

	column TotalWorkingYears
		dataType: int64
		formatString: 0
		lineageTag: 14913c4a-4b78-4373-b020-d7f2d0bc15c1
		summarizeBy: sum
		sourceColumn: TotalWorkingYears

		annotation SummarizationSetBy = Automatic

	column TrainingTimesLastYear
		dataType: int64
		formatString: 0
		lineageTag: 56392884-ef98-4aba-9ea5-32222459cd75
		summarizeBy: sum
		sourceColumn: TrainingTimesLastYear

		annotation SummarizationSetBy = Automatic

	column WorkLifeBalance
		dataType: int64
		formatString: 0
		lineageTag: 2031f82c-832c-4cb5-a741-ab5d1bba4065
		summarizeBy: sum
		sourceColumn: WorkLifeBalance

		annotation SummarizationSetBy = Automatic

	column YearsAtCompany
		dataType: int64
		formatString: 0
		lineageTag: 426e907c-0409-49e6-acf4-925d2da27400
		summarizeBy: sum
		sourceColumn: YearsAtCompany

		annotation SummarizationSetBy = Automatic

	column YearsInCurrentRole
		dataType: int64
		formatString: 0
		lineageTag: 15bab8c4-fd9c-445c-93ff-8fdcc4cc1152
		summarizeBy: sum
		sourceColumn: YearsInCurrentRole

		annotation SummarizationSetBy = Automatic

	column YearsSinceLastPromotion
		dataType: int64
		formatString: 0
		lineageTag: ab3576aa-43e5-427b-a152-59db9417cf52
		summarizeBy: sum
		sourceColumn: YearsSinceLastPromotion

		annotation SummarizationSetBy = Automatic

	column AttritionCount
		dataType: int64
		formatString: 0
		lineageTag: d86fe8c0-9d1f-4c34-831a-6408905a26c8
		summarizeBy: sum
		sourceColumn: AttritionCount

		annotation SummarizationSetBy = Automatic

	partition HR_Analytics = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\HP\OneDrive\Desktop\Power bI project\HR_Analytics.xlsx"), null, true),
				    HR_Analytics_Sheet = Source{[Item="HR_Analytics",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(HR_Analytics_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"EmpID", type text}, {"Age", Int64.Type}, {"AgeGroup", type text}, {"Attrition", type text}, {"BusinessTravel", type text}, {"DailyRate", Int64.Type}, {"Department", type text}, {"DistanceFromHome", Int64.Type}, {"Education", Int64.Type}, {"EducationField", type text}, {"EmployeeCount", Int64.Type}, {"EmployeeNumber", Int64.Type}, {"EnvironmentSatisfaction", Int64.Type}, {"Gender", type text}, {"HourlyRate", Int64.Type}, {"JobInvolvement", Int64.Type}, {"JobLevel", Int64.Type}, {"JobRole", type text}, {"JobSatisfaction", Int64.Type}, {"MaritalStatus", type text}, {"MonthlyIncome", Int64.Type}, {"SalarySlab", type text}, {"MonthlyRate", Int64.Type}, {"NumCompaniesWorked", Int64.Type}, {"Over18", type text}, {"OverTime", type text}, {"PercentSalaryHike", Int64.Type}, {"PerformanceRating", Int64.Type}, {"RelationshipSatisfaction", Int64.Type}, {"StandardHours", Int64.Type}, {"StockOptionLevel", Int64.Type}, {"TotalWorkingYears", Int64.Type}, {"TrainingTimesLastYear", Int64.Type}, {"WorkLifeBalance", Int64.Type}, {"YearsAtCompany", Int64.Type}, {"YearsInCurrentRole", Int64.Type}, {"YearsSinceLastPromotion", Int64.Type}, {"YearsWithCurrManager", Int64.Type}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"YearsWithCurrManager"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Columns"),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Duplicates", each true),
				    #"Replaced Value" = Table.ReplaceValue(#"Filtered Rows","TravelRarely","Travel_Rarely",Replacer.ReplaceText,{"BusinessTravel"}),
				    #"Filtered Rows1" = Table.SelectRows(#"Replaced Value", each true),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Filtered Rows1",{{"EmpID", type text}, {"Age", Int64.Type}, {"AgeGroup", type text}, {"Attrition", type text}, {"BusinessTravel", type text}, {"DailyRate", Int64.Type}, {"Department", type text}, {"DistanceFromHome", Int64.Type}, {"Education", Int64.Type}, {"EducationField", type text}, {"EmployeeCount", Int64.Type}, {"EmployeeNumber", Int64.Type}, {"EnvironmentSatisfaction", Int64.Type}, {"Gender", type text}, {"HourlyRate", Int64.Type}, {"JobInvolvement", Int64.Type}, {"JobLevel", Int64.Type}, {"JobRole", type text}, {"JobSatisfaction", Int64.Type}, {"MaritalStatus", type text}, {"MonthlyIncome", Int64.Type}, {"SalarySlab", type text}, {"MonthlyRate", Int64.Type}, {"NumCompaniesWorked", Int64.Type}, {"Over18", type text}, {"OverTime", type text}, {"PercentSalaryHike", Int64.Type}, {"PerformanceRating", Int64.Type}, {"RelationshipSatisfaction", Int64.Type}, {"StandardHours", Int64.Type}, {"StockOptionLevel", Int64.Type}, {"TotalWorkingYears", Int64.Type}, {"TrainingTimesLastYear", Int64.Type}, {"WorkLifeBalance", Int64.Type}, {"YearsAtCompany", Int64.Type}, {"YearsInCurrentRole", Int64.Type}, {"YearsSinceLastPromotion", Int64.Type}}),
				    #"Added Conditional Column" = Table.AddColumn(#"Changed Type1", "AttrationCount", each if [Attrition] = "yes" then 1 else 0),
				    #"Removed Columns1" = Table.RemoveColumns(#"Added Conditional Column",{"AttrationCount"}),
				    #"Added Conditional Column1" = Table.AddColumn(#"Removed Columns1", "AttritionCount", each if [Attrition] = "yes" then 1 else 0),
				    #"Removed Columns2" = Table.RemoveColumns(#"Added Conditional Column1",{"AttritionCount"}),
				    #"Added Conditional Column2" = Table.AddColumn(#"Removed Columns2", "AttritionCount", each if [Attrition] = "ture" then 1 else 0),
				    #"Filtered Rows2" = Table.SelectRows(#"Added Conditional Column2", each true),
				    #"Removed Columns3" = Table.RemoveColumns(#"Filtered Rows2",{"AttritionCount"}),
				    #"Added Conditional Column3" = Table.AddColumn(#"Removed Columns3", "AttritionCount", each if [Attrition] = "true" then 1 else 0),
				    #"Filtered Rows3" = Table.SelectRows(#"Added Conditional Column3", each true),
				    #"Removed Columns4" = Table.RemoveColumns(#"Filtered Rows3",{"AttritionCount"}),
				    #"Added Conditional Column4" = Table.AddColumn(#"Removed Columns4", "AttritionCount", each if [Attrition] = "Yes" then 1 else 0),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Conditional Column4",{{"EmpID", type text}, {"Age", Int64.Type}, {"AgeGroup", type text}, {"Attrition", type text}, {"BusinessTravel", type text}, {"DailyRate", Int64.Type}, {"Department", type text}, {"DistanceFromHome", Int64.Type}, {"Education", Int64.Type}, {"EducationField", type text}, {"EmployeeCount", Int64.Type}, {"EmployeeNumber", Int64.Type}, {"EnvironmentSatisfaction", Int64.Type}, {"Gender", type text}, {"HourlyRate", Int64.Type}, {"JobInvolvement", Int64.Type}, {"JobLevel", Int64.Type}, {"JobRole", type text}, {"JobSatisfaction", Int64.Type}, {"MaritalStatus", type text}, {"MonthlyIncome", Int64.Type}, {"SalarySlab", type text}, {"MonthlyRate", Int64.Type}, {"NumCompaniesWorked", Int64.Type}, {"Over18", type text}, {"OverTime", type text}, {"PercentSalaryHike", Int64.Type}, {"PerformanceRating", Int64.Type}, {"RelationshipSatisfaction", Int64.Type}, {"StandardHours", Int64.Type}, {"StockOptionLevel", Int64.Type}, {"TotalWorkingYears", Int64.Type}, {"TrainingTimesLastYear", Int64.Type}, {"WorkLifeBalance", Int64.Type}, {"YearsAtCompany", Int64.Type}, {"YearsInCurrentRole", Int64.Type}, {"YearsSinceLastPromotion", Int64.Type}, {"AttritionCount", Int64.Type}})
				in
				    #"Changed Type2"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

